import type { Metadata } from "next"
import "../globals.css"
import { Header } from "@/app/components/header"
import { Footer } from "@/app/components/footer"

type AuthLayoutProps = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function AuthLayout({ children }: AuthLayoutProps) {
  return (
    <html lang="ru">
      <body>
        <div className="grid bg-gradient grid-rows-[auto_1fr_auto] min-h-svh">
          <Header className="!bg-transparent text-primary-foreground" />
          {children}
          <Footer className="bg-primary text-primary-foreground rounded-t-3xl" />
        </div>
      </body>
    </html>
  )
}
